language: objective-c

osx_image: xcode9.1

env:
  matrix:
    - TEST_PLATFORM="platform=iOS Simulator,OS=8.1,name=iPhone 5s"
    - TEST_PLATFORM="platform=iOS Simulator,OS=9.0,name=iPhone 6"

rvm:
    - 2.2.2

before_install:
    - gem install cocoapods -v '1.4.0'
    - gem install slather
    - gem install xcpretty -N --no-ri --no-rdoc
    - pod install --repo-update

script:
    - set -o pipefail
    - xcodebuild clean test -sdk iphonesimulator -destination "${TEST_PLATFORM}" -workspace Snowplow.xcworkspace -scheme Snowplow CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO | xcpretty

after_success: slather
